name: Update

on: [push]

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: |
          ~/.cache/pip
          env/
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip2-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip2-
          ${{ runner.os }}-
    - name: Install dependencies
      run: make create-install
    - name: Run Job
      run: source env/bin/activate && inv update

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        # This should only have access to API_TOKEN_GITHUB
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'scratch/*.csv.gz'
        destination_repo: 'tianhuil/pywiki-data'
        destination_folder: 'wordcount/simplewiki'
        destination_branch: 'main'
        user_email: 'tianhuil@github.com'
        user_name: 'tianhuil'
